### your site title here

title: advantAge Seniors
description: The vision for advantAGE seniors has evolved through many years of social gerontology practice to truly capture the devotion, quality and comfort we know you and your family deserve when it comes to aged care.
baseurl: /advantage-seniors

### exclude the instructions / write-up in the README.md

exclude:
- README.md
