### your site title here

title: engAge Seniors
description: The vision for advantAGE seniors has evolved through many years of social gerontology practice to truly capture the devotion, quality and comfort we know you and your family deserve when it comes to aged care.

phone: +91 98444 95527
email: name@email.com

facebook: https://www.facebook.com/Advantage-Seniors-Consulting-1671134279867943/
linkedin: 
twitter:
google-plus:


baseurl: /engage-seniors


include:
 - _pages

### exclude the instructions / write-up in the README.md

exclude:
- README.md
- raw
