### your site title here

title: engAge Seniors
description: The vision for engAGE seniors has evolved through many years of social gerontology practice to provide commitment, quality and expertise. We know you and your family deserve much more when it comes to aged care.

phone: +91 966 337 7762
email-1: advantagejacob@gmail.com
email-2: renjukb18@gmail.com

facebook: https://www.facebook.com/Advantage-Seniors-Consulting-1671134279867943/
linkedin:
twitter:
google-plus:


baseurl: /engage-seniors


include:
 - _pages

### exclude the instructions / write-up in the README.md

exclude:
- README.md
- raw
